/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.lpiu.interfaces;

import br.cesjf.lpiu.arquivos.associacao.ArquivoInAssociacao;
import br.cesjf.lpiu.arquivos.pessoas.ArquivoInPessoa;
import br.cesjf.lpiu.arquivos.carros.ArquivoInCarro;
import br.cesjf.lpiu.arquivos.associacao.ArquivoOutAssociacao;
import br.cesjf.lpiu.arquivos.pessoas.ArquivoOutPessoa;
import br.cesjf.lpiu.arquivos.carros.ArquivoOutCarro;
import br.cesjf.lpiu.modelo.Pessoas;
import br.cesjf.lpiu.modelo.Automovel;
import br.cesjf.lpiu.modelo.Associacao;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jovany
 */
public class Associacoes extends javax.swing.JFrame {

    private ArquivoInAssociacao arqinAssociacao = new ArquivoInAssociacao();
    private ArquivoOutAssociacao arqoutAssociacao = new ArquivoOutAssociacao();
    public Associacao associacao = null;
    int linhaAssociacao;

    private ArquivoInPessoa arqinPessoa = new ArquivoInPessoa();
    public Pessoas pessoa = null;
    int linhaPessoa;

    private ArquivoInCarro arqinVeiculo = new ArquivoInCarro();
    public Automovel automovel = null;
    int linhaVeiculo;

    public Associacoes() {
        initComponents();
        associacao = new Associacao();
        try {
            arqoutAssociacao.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Associacoes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Associacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void limpar() {
        txtPlaca.setText("");
        txtCnh.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        btAssociar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtAssociacao = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCnh = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtVeiculos = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtPessoas = new javax.swing.JTable();
        btLimpar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btAssociar.setText("Associar veículo");
        btAssociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAssociarActionPerformed(evt);
            }
        });

        jtAssociacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa do Veículo", "CNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAssociacao.getTableHeader().setReorderingAllowed(false);
        jtAssociacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAssociacaoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtAssociacao);
        if (jtAssociacao.getColumnModel().getColumnCount() > 0) {
            jtAssociacao.getColumnModel().getColumn(0).setHeaderValue("Pessoas");
            jtAssociacao.getColumnModel().getColumn(1).setHeaderValue("CNH");
        }

        btExcluir.setText("Excluír Associação");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar Associação");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        jLabel1.setText("Placa do Veículo:");

        jLabel2.setText("CNH do Condutor:");

        jtVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Ano Fabricação", "Motorização", "Valor Básico", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVeiculos.getTableHeader().setReorderingAllowed(false);
        jtVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVeiculosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jtVeiculos);

        jtPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Nascimento", "CNH", "Endereço", "Bairro", "Numero", "Complemento", "Cidade", "Estado", "Cep"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPessoas.getTableHeader().setReorderingAllowed(false);
        jtPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPessoasMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jtPessoas);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCnh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAssociar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btLimpar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(btAssociar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAssociacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAssociacaoMouseClicked
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
        linhaAssociacao = jtAssociacao.getSelectedRow();

        txtPlaca.setText(jtAssociacao.getValueAt(linhaAssociacao, 0).toString());
        txtCnh.setText(jtAssociacao.getValueAt(linhaAssociacao, 1).toString());
    }//GEN-LAST:event_jtAssociacaoMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jtAssociacao.getModel();
        List<Associacao> list = new ArrayList<Associacao>();
        ArrayList<Associacao> nova_list = new ArrayList<Associacao>();
        linhaAssociacao = jtAssociacao.getSelectedRow();
        Object valor = modelo.getValueAt(linhaAssociacao, 0);
        list = arqinAssociacao.getTodasAssociacoes();

        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getPlacaVeiculo().equals(valor))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqoutAssociacao.recadastrar_todas(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(Associacoes.class.getName()).log(Level.SEVERE, null, ex);
        }

        modelo.removeRow(linhaAssociacao);
        JOptionPane.showMessageDialog(null, "Registro apagado com sucesso");

        limpar();

        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int cont = 1;

        // Listar dados das pessoas na tabela Pessoas
        List<Pessoas> listaPessoa = new ArrayList<Pessoas>();

        listaPessoa = arqinPessoa.getTodasPessoas();
        DefaultTableModel modeloPessoa = (DefaultTableModel) jtPessoas.getModel();

        for (int i = jtPessoas.getRowCount() - 1; i >= 0; --i) {
            modeloPessoa.removeRow(i);
        }

        for (int i = 0; i < listaPessoa.size(); i++) {
            modeloPessoa.addRow(listaPessoa.get(i).getPessoa());
            cont++;
        }        // TODO add your handling code here:

        // Listar dados dos veículos na tabela Veículos
        List<Automovel> listaAutomovel = new ArrayList<Automovel>();

        listaAutomovel = arqinVeiculo.getTodosCarros();
        DefaultTableModel modeloAutomovel = (DefaultTableModel) jtVeiculos.getModel();

        for (int i = jtVeiculos.getRowCount() - 1; i >= 0; --i) {
            modeloAutomovel.removeRow(i);
        }

        for (int i = 0; i < listaAutomovel.size(); i++) {
            modeloAutomovel.addRow(listaAutomovel.get(i).getcarro());
            cont++;
        }

        // Listar dados das associações na tabela Associação 
        List<Associacao> listaAssociacao = new ArrayList<Associacao>();

        listaAssociacao = arqinAssociacao.getTodasAssociacoes();
        DefaultTableModel modeloAssociacao = (DefaultTableModel) jtAssociacao.getModel();

        for (int i = jtAssociacao.getRowCount() - 1; i >= 0; --i) {
            modeloAssociacao.removeRow(i);
        }

        for (int i = 0; i < listaAssociacao.size(); i++) {
            modeloAssociacao.addRow(listaAssociacao.get(i).getAssociacao());
            cont++;
        }

    }//GEN-LAST:event_formWindowOpened

    private void jtVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVeiculosMouseClicked
        linhaVeiculo = jtVeiculos.getSelectedRow();

        txtPlaca.setText(jtVeiculos.getValueAt(linhaVeiculo, 0).toString());
    }//GEN-LAST:event_jtVeiculosMouseClicked

    private void jtPessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPessoasMouseClicked
        linhaPessoa = jtPessoas.getSelectedRow();

        txtCnh.setText(jtPessoas.getValueAt(linhaPessoa, 2).toString());
    }//GEN-LAST:event_jtPessoasMouseClicked

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        
        ArrayList<Associacao> listAssociacao = new ArrayList<>();
        listAssociacao = (ArrayList<Associacao>) arqinAssociacao.getTodasAssociacoes();
        
        listAssociacao.get(linhaAssociacao).setPlacaVeiculo(txtPlaca.getText());
        listAssociacao.get(linhaAssociacao).setCnhCondutor(txtCnh.getText());

        try{
            arqoutAssociacao.recadastrar_todas(listAssociacao);
        }catch (IOException ex) {
            Logger.getLogger(Associacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!");
        
        limpar();
        
        DefaultTableModel modelo = (DefaultTableModel) jtAssociacao.getModel();
        
        if (jtAssociacao.getRowCount() > 0) {
            for (int i = jtAssociacao.getRowCount() - 1; i>0; i--){
                modelo.removeRow(i);
            }
        }
        
        List<Associacao> listAuto2 = new ArrayList<>();
        listAuto2 = arqinAssociacao.getTodasAssociacoes();
        
        for (int i=0; i< listAuto2.size(); i++){
            modelo.addRow(listAuto2.get(i).getAssociacao());
        }
        
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);                                             // TODO add your handling code here:
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAssociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAssociarActionPerformed
        associacao = new Associacao();
        associacao.setPlacaVeiculo(txtPlaca.getText());
        associacao.setCnhCondutor(txtCnh.getText());

        try {
            arqoutAssociacao.Adicionar(associacao);
        } catch (IOException ex) {
            Logger.getLogger(Associacoes.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(
                null, "Associacao inserida com sucesso!");

        limpar();

        int cont = 1;

        List<Associacao> listacar = new ArrayList<Associacao>();

        listacar = arqinAssociacao.getTodasAssociacoes();
        DefaultTableModel modeloAssocicao = (DefaultTableModel) jtAssociacao.getModel();

        for (int i = jtAssociacao.getRowCount() - 1;
                i >= 0; --i) {
            modeloAssocicao.removeRow(i);
        }

        for (int i = 0;
                i < listacar.size();
                i++) {
            modeloAssocicao.addRow(listacar.get(i).getAssociacao());
            cont++;
        }
    }//GEN-LAST:event_btAssociarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Associacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Associacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Associacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Associacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Associacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAssociar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jtAssociacao;
    private javax.swing.JTable jtCarro;
    private javax.swing.JTable jtCarro1;
    private javax.swing.JTable jtPessoas;
    private javax.swing.JTable jtVeiculos;
    private javax.swing.JTextField txtCnh;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
