/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cesjf.lpiu.interfaces;

import br.cesjf.lpiu.arquivos.carros.ArquivoInCarro;
import br.cesjf.lpiu.arquivos.carros.ArquivoOutCarro;
import br.cesjf.lpiu.modelo.Automovel;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tassio
 */
public class CadCarro extends javax.swing.JFrame {

    private ArquivoInCarro arqin = new ArquivoInCarro();
    private ArquivoOutCarro arqout = new ArquivoOutCarro();
    int linha;

    /**
     * Creates new form CadCarro
     */
    public CadCarro() {
        initComponents();
        auto = new Automovel();
        try {
            arqout.abrir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Automovel auto = null;

    public void limpar() {
        txtPlaca.setText("");
        txtModelo.setText("");
        txtData.setText("");
        txtValorBasico.setText("");
        comboMotorizacao.setSelectedIndex(-1);
        txtAliquota.setText("");
        txtImposto.setText("");
        txtValorBasico.setText("");
        txtValorTotal.setText("");
        btTipoCarro.clearSelection();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTipoCarro = new javax.swing.ButtonGroup();
        btLimpar = new javax.swing.JButton();
        rbCarga = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboMotorizacao = new javax.swing.JComboBox<>();
        jbAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAliquota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbUtilitario = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtImposto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rbPasseio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtValorBasico = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JFormattedTextField();
        btCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCarro = new javax.swing.JTable();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btTipoCarro.add(rbCarga);
        rbCarga.setText("Carga");

        jLabel1.setText("Placa");

        txtValorTotal.setEnabled(false);

        jLabel10.setText("Dados do Automovel");

        comboMotorizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.4", "1.6", "1.8", "2.0" }));
        comboMotorizacao.setToolTipText("");
        comboMotorizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMotorizacaoActionPerformed(evt);
            }
        });

        jbAdd.setText("Adicionar");
        jbAdd.setEnabled(false);
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jLabel3.setText("Ano de fabricação");

        jLabel7.setText("Aliquota de imposto");

        jLabel2.setText("Modelo");

        jLabel8.setText("Imposto a pagar");

        jLabel5.setText("Valor Basico");

        btTipoCarro.add(rbUtilitario);
        rbUtilitario.setText("Utilitario");

        jLabel6.setText("    Categoria");

        txtImposto.setEnabled(false);

        jLabel9.setText("Valor total de compra");

        btTipoCarro.add(rbPasseio);
        rbPasseio.setText("Passeio");
        rbPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPasseioActionPerformed(evt);
            }
        });

        jLabel4.setText("Motorizacao");

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        jtCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Ano Fabricação", "Motorização", "Valor Básico", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCarro.getTableHeader().setReorderingAllowed(false);
        jtCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCarroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCarro);

        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbPasseio)
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbUtilitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65)
                                .addComponent(rbCarga))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(46, 46, 46)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(comboMotorizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txtImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAliquota, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPlaca)
                    .addComponent(txtModelo))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMotorizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPasseio)
                    .addComponent(rbUtilitario)
                    .addComponent(rbCarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAliquota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal princ = new Principal();
        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void comboMotorizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMotorizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMotorizacaoActionPerformed

    private void rbPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPasseioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPasseioActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed

        Double valorBasico = Double.parseDouble(txtValorBasico.getText());
        Double aliquota = Double.parseDouble(txtAliquota.getText());

        Double imposto = auto.calcularImposto(valorBasico, aliquota);
        txtImposto.setText(imposto.toString());

        txtValorTotal.setText(String.valueOf(auto.calcularValorTotal(valorBasico, imposto)));

        jbAdd.setEnabled(true);


    }//GEN-LAST:event_btCalcularActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
           
        auto = new Automovel();
        auto.setPlaca(txtPlaca.getText());
        auto.setModelo(txtModelo.getText());
        auto.setData(txtData.getText());
        auto.setValorBasico(Double.parseDouble(txtValorBasico.getText()));
        auto.setMotorizacao((String) comboMotorizacao.getSelectedItem());

        rbCarga.setActionCommand("Carga");
        rbPasseio.setActionCommand("Passeio");
        rbUtilitario.setActionCommand("Utilitario");

        auto.setCategoria(btTipoCarro.getSelection().getActionCommand());

        try {
            arqout.Adicionar(auto);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(
                null, "Carro Inserido com sucesso!");
        
        limpar();
        jbAdd.setEnabled(false);
        
        int cont = 1;

        List<Automovel> listacar = new ArrayList<Automovel>();

        listacar = arqin.getTodosCarros();
        DefaultTableModel modelocarro = (DefaultTableModel) jtCarro.getModel();

        for (int i = jtCarro.getRowCount() - 1;
                i >= 0; --i) {
            modelocarro.removeRow(i);
        }

        for (int i = 0;
                i < listacar.size();
                i++) {
            modelocarro.addRow(listacar.get(i).getcarro());
            cont++;
        }

    }//GEN-LAST:event_jbAddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int cont = 1;

        List<Automovel> listacar = new ArrayList<Automovel>();

        listacar = arqin.getTodosCarros();
        DefaultTableModel modelocarro = (DefaultTableModel) jtCarro.getModel();

        for (int i = jtCarro.getRowCount() - 1; i >= 0; --i) {
            modelocarro.removeRow(i);
        }

        for (int i = 0; i < listacar.size(); i++) {
            modelocarro.addRow(listacar.get(i).getcarro());
            cont++;
        }
    }//GEN-LAST:event_formWindowOpened

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
       //Começa a alterar
        ArrayList<Automovel> listAuto = new ArrayList<>();
        listAuto = (ArrayList<Automovel>) arqin.getTodosCarros();
        
        rbCarga.setActionCommand("Carga");
        rbPasseio.setActionCommand("Passeio");
        rbUtilitario.setActionCommand("Utilitario");

        auto.setCategoria(btTipoCarro.getSelection().getActionCommand());
        
        listAuto.get(linha).setPlaca(txtPlaca.getText());
        listAuto.get(linha).setModelo(txtModelo.getText());
        listAuto.get(linha).setData(txtData.getText());
        listAuto.get(linha).setValorBasico(Double.parseDouble(txtValorBasico.getText()));
        listAuto.get(linha).setMotorizacao((String) comboMotorizacao.getSelectedItem());
        listAuto.get(linha).setCategoria(btTipoCarro.getSelection().getActionCommand());
           
        try{
           arqout.recadastrar_todos(listAuto);
        }catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!");
        
        limpar();
        
        DefaultTableModel modelo = (DefaultTableModel) jtCarro.getModel();
        
            if (jtCarro.getRowCount() > 0) {
            for (int i = jtCarro.getRowCount() - 1; i>0; i--){
                modelo.removeRow(i);
            }
        }
        
        List<Automovel> listAuto2 = new ArrayList<>();
        listAuto2 = arqin.getTodosCarros();
        
        for (int i=0; i< listAuto2.size(); i++){
            modelo.addRow(listAuto2.get(i).getcarro());
        }
        
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) jtCarro.getModel();
        List<Automovel> list = new ArrayList<Automovel>();
        ArrayList<Automovel> nova_list = new ArrayList<Automovel>();
        linha = jtCarro.getSelectedRow();
        Object valor = modelo.getValueAt(linha, 0);
        list = arqin.getTodosCarros();

        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getPlaca().equals(valor))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqout.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(CadCarro.class.getName()).log(Level.SEVERE, null, ex);
        }

        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(null, "Registro apagado com sucesso");

        limpar();
         
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jtCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCarroMouseClicked

        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
        linha = jtCarro.getSelectedRow();

        txtPlaca.setText(jtCarro.getValueAt(linha, 0).toString());
        txtModelo.setText(jtCarro.getValueAt(linha, 1).toString());
        txtData.setText(jtCarro.getValueAt(linha, 2).toString());

        String motorizacao = jtCarro.getValueAt(linha, 3).toString();

        switch (motorizacao) {
            case "1.0":
                comboMotorizacao.setSelectedIndex(0);
                break;
            case "1.4":
                comboMotorizacao.setSelectedIndex(1);
                break;
            case "1.6":
                comboMotorizacao.setSelectedIndex(2);
                break;
            case "1.8":
                comboMotorizacao.setSelectedIndex(3);
                break;
            case "2.0":
                comboMotorizacao.setSelectedIndex(4);
                break;
            default:
                comboMotorizacao.setSelectedIndex(-1);
                break;
        }

        txtValorBasico.setText(jtCarro.getValueAt(linha, 4).toString());

        String tipo = jtCarro.getValueAt(linha, 5).toString();

        if (tipo.equals("Carga")) {
            rbCarga.setSelected(true);
        } else if (tipo.equals("Passeio")) {
            rbPasseio.setSelected(true);
        } else {
            rbUtilitario.setSelected(true);
        }
    }//GEN-LAST:event_jtCarroMouseClicked

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCarro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup btTipoCarro;
    private javax.swing.JComboBox<String> comboMotorizacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdd;
    private javax.swing.JTable jtCarro;
    private javax.swing.JRadioButton rbCarga;
    private javax.swing.JRadioButton rbPasseio;
    private javax.swing.JRadioButton rbUtilitario;
    private javax.swing.JTextField txtAliquota;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtImposto;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtPlaca;
    private javax.swing.JTextField txtValorBasico;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
